

INSERT INTO `quan` (`q_id`, `q_ten`, `q_mota`, `t_id`, `created_at`, `updated_at`) VALUES
(1, 'Quận Ba Đình', 'Quận', 1, NULL, NULL),
(2, 'Quận Hoàn Kiếm', 'Quận', 1, NULL, NULL),
(3, 'Quận Tây Hồ', 'Quận', 1, NULL, NULL),
(4, 'Quận Long Biên', 'Quận', 1, NULL, NULL),
(5, 'Quận Cầu Giấy', 'Quận', 1, NULL, NULL),
(6, 'Quận Đống Đa', 'Quận', 1, NULL, NULL),
(7, 'Quận Hai Bà Trưng', 'Quận', 1, NULL, NULL),
(8, 'Quận Hoàng Mai', 'Quận', 1, NULL, NULL),
(9, 'Quận Thanh Xuân', 'Quận', 1, NULL, NULL),
(16, 'Huyện Sóc Sơn', 'Huyện', 1, NULL, NULL),
(17, 'Huyện Đông Anh', 'Huyện', 1, NULL, NULL),
(18, 'Huyện Gia Lâm', 'Huyện', 1, NULL, NULL),
(19, 'Quận Nam Từ Liêm', 'Quận', 1, NULL, NULL),
(20, 'Huyện Thanh Trì', 'Huyện', 1, NULL, NULL),
(21, 'Quận Bắc Từ Liêm', 'Quận', 1, NULL, NULL),
(24, 'Thành phố Hà Giang', 'Thành phố', 2, NULL, NULL),
(26, 'Huyện Đồng Văn', 'Huyện', 2, NULL, NULL),
(27, 'Huyện Mèo Vạc', 'Huyện', 2, NULL, NULL),
(28, 'Huyện Yên Minh', 'Huyện', 2, NULL, NULL),
(29, 'Huyện Quản Bạ', 'Huyện', 2, NULL, NULL),
(30, 'Huyện Vị Xuyên', 'Huyện', 2, NULL, NULL),
(31, 'Huyện Bắc Mê', 'Huyện', 2, NULL, NULL),
(32, 'Huyện Hoàng Su Phì', 'Huyện', 2, NULL, NULL),
(33, 'Huyện Xín Mần', 'Huyện', 2, NULL, NULL),
(34, 'Huyện Bắc Quang', 'Huyện', 2, NULL, NULL),
(35, 'Huyện Quang Bình', 'Huyện', 2, NULL, NULL),
(40, 'Thành phố Cao Bằng', 'Thành phố', 4, NULL, NULL),
(42, 'Huyện Bảo Lâm', 'Huyện', 4, NULL, NULL),
(43, 'Huyện Bảo Lạc', 'Huyện', 4, NULL, NULL),
(44, 'Huyện Thông Nông', 'Huyện', 4, NULL, NULL),
(45, 'Huyện Hà Quảng', 'Huyện', 4, NULL, NULL),
(46, 'Huyện Trà Lĩnh', 'Huyện', 4, NULL, NULL),
(47, 'Huyện Trùng Khánh', 'Huyện', 4, NULL, NULL),
(48, 'Huyện Hạ Lang', 'Huyện', 4, NULL, NULL),
(49, 'Huyện Quảng Uyên', 'Huyện', 4, NULL, NULL),
(50, 'Huyện Phục Hoà', 'Huyện', 4, NULL, NULL),
(51, 'Huyện Hoà An', 'Huyện', 4, NULL, NULL),
(52, 'Huyện Nguyên Bình', 'Huyện', 4, NULL, NULL),
(53, 'Huyện Thạch An', 'Huyện', 4, NULL, NULL),
(58, 'Thành Phố Bắc Kạn', 'Thành phố', 6, NULL, NULL),
(60, 'Huyện Pác Nặm', 'Huyện', 6, NULL, NULL),
(61, 'Huyện Ba Bể', 'Huyện', 6, NULL, NULL),
(62, 'Huyện Ngân Sơn', 'Huyện', 6, NULL, NULL),
(63, 'Huyện Bạch Thông', 'Huyện', 6, NULL, NULL),
(64, 'Huyện Chợ Đồn', 'Huyện', 6, NULL, NULL),
(65, 'Huyện Chợ Mới', 'Huyện', 6, NULL, NULL),
(66, 'Huyện Na Rì', 'Huyện', 6, NULL, NULL),
(70, 'Thành phố Tuyên Quang', 'Thành phố', 8, NULL, NULL),
(71, 'Huyện Lâm Bình', 'Huyện', 8, NULL, NULL),
(72, 'Huyện Nà Hang', 'Huyện', 8, NULL, NULL),
(73, 'Huyện Chiêm Hóa', 'Huyện', 8, NULL, NULL),
(74, 'Huyện Hàm Yên', 'Huyện', 8, NULL, NULL),
(75, 'Huyện Yên Sơn', 'Huyện', 8, NULL, NULL),
(76, 'Huyện Sơn Dương', 'Huyện', 8, NULL, NULL),
(80, 'Thành phố Lào Cai', 'Thành phố', 10, NULL, NULL),
(82, 'Huyện Bát Xát', 'Huyện', 10, NULL, NULL),
(83, 'Huyện Mường Khương', 'Huyện', 10, NULL, NULL),
(84, 'Huyện Si Ma Cai', 'Huyện', 10, NULL, NULL),
(85, 'Huyện Bắc Hà', 'Huyện', 10, NULL, NULL),
(86, 'Huyện Bảo Thắng', 'Huyện', 10, NULL, NULL),
(87, 'Huyện Bảo Yên', 'Huyện', 10, NULL, NULL),
(88, 'Huyện Sa Pa', 'Huyện', 10, NULL, NULL),
(89, 'Huyện Văn Bàn', 'Huyện', 10, NULL, NULL),
(94, 'Thành phố Điện Biên Phủ', 'Thành phố', 11, NULL, NULL),
(95, 'Thị Xã Mường Lay', 'Thị xã', 11, NULL, NULL),
(96, 'Huyện Mường Nhé', 'Huyện', 11, NULL, NULL),
(97, 'Huyện Mường Chà', 'Huyện', 11, NULL, NULL),
(98, 'Huyện Tủa Chùa', 'Huyện', 11, NULL, NULL),
(99, 'Huyện Tuần Giáo', 'Huyện', 11, NULL, NULL),
(100, 'Huyện Điện Biên', 'Huyện', 11, NULL, NULL),
(101, 'Huyện Điện Biên Đông', 'Huyện', 11, NULL, NULL),
(102, 'Huyện Mường Ảng', 'Huyện', 11, NULL, NULL),
(103, 'Huyện Nậm Pồ', 'Huyện', 11, NULL, NULL),
(105, 'Thành phố Lai Châu', 'Thành phố', 12, NULL, NULL),
(106, 'Huyện Tam Đường', 'Huyện', 12, NULL, NULL),
(107, 'Huyện Mường Tè', 'Huyện', 12, NULL, NULL),
(108, 'Huyện Sìn Hồ', 'Huyện', 12, NULL, NULL),
(109, 'Huyện Phong Thổ', 'Huyện', 12, NULL, NULL),
(110, 'Huyện Than Uyên', 'Huyện', 12, NULL, NULL),
(111, 'Huyện Tân Uyên', 'Huyện', 12, NULL, NULL),
(112, 'Huyện Nậm Nhùn', 'Huyện', 12, NULL, NULL),
(116, 'Thành phố Sơn La', 'Thành phố', 14, NULL, NULL),
(118, 'Huyện Quỳnh Nhai', 'Huyện', 14, NULL, NULL),
(119, 'Huyện Thuận Châu', 'Huyện', 14, NULL, NULL),
(120, 'Huyện Mường La', 'Huyện', 14, NULL, NULL),
(121, 'Huyện Bắc Yên', 'Huyện', 14, NULL, NULL),
(122, 'Huyện Phù Yên', 'Huyện', 14, NULL, NULL),
(123, 'Huyện Mộc Châu', 'Huyện', 14, NULL, NULL),
(124, 'Huyện Yên Châu', 'Huyện', 14, NULL, NULL),
(125, 'Huyện Mai Sơn', 'Huyện', 14, NULL, NULL),
(126, 'Huyện Sông Mã', 'Huyện', 14, NULL, NULL),
(127, 'Huyện Sốp Cộp', 'Huyện', 14, NULL, NULL),
(128, 'Huyện Vân Hồ', 'Huyện', 14, NULL, NULL),
(132, 'Thành phố Yên Bái', 'Thành phố', 15, NULL, NULL),
(133, 'Thị xã Nghĩa Lộ', 'Thị xã', 15, NULL, NULL),
(135, 'Huyện Lục Yên', 'Huyện', 15, NULL, NULL),
(136, 'Huyện Văn Yên', 'Huyện', 15, NULL, NULL),
(137, 'Huyện Mù Căng Chải', 'Huyện', 15, NULL, NULL),
(138, 'Huyện Trấn Yên', 'Huyện', 15, NULL, NULL),
(139, 'Huyện Trạm Tấu', 'Huyện', 15, NULL, NULL),
(140, 'Huyện Văn Chấn', 'Huyện', 15, NULL, NULL),
(141, 'Huyện Yên Bình', 'Huyện', 15, NULL, NULL),
(148, 'Thành phố Hòa Bình', 'Thành phố', 17, NULL, NULL),
(150, 'Huyện Đà Bắc', 'Huyện', 17, NULL, NULL),
(151, 'Huyện Kỳ Sơn', 'Huyện', 17, NULL, NULL),
(152, 'Huyện Lương Sơn', 'Huyện', 17, NULL, NULL),
(153, 'Huyện Kim Bôi', 'Huyện', 17, NULL, NULL),
(154, 'Huyện Cao Phong', 'Huyện', 17, NULL, NULL),
(155, 'Huyện Tân Lạc', 'Huyện', 17, NULL, NULL),
(156, 'Huyện Mai Châu', 'Huyện', 17, NULL, NULL),
(157, 'Huyện Lạc Sơn', 'Huyện', 17, NULL, NULL),
(158, 'Huyện Yên Thủy', 'Huyện', 17, NULL, NULL),
(159, 'Huyện Lạc Thủy', 'Huyện', 17, NULL, NULL),
(164, 'Thành phố Thái Nguyên', 'Thành phố', 19, NULL, NULL),
(165, 'Thành phố Sông Công', 'Thành phố', 19, NULL, NULL),
(167, 'Huyện Định Hóa', 'Huyện', 19, NULL, NULL),
(168, 'Huyện Phú Lương', 'Huyện', 19, NULL, NULL),
(169, 'Huyện Đồng Hỷ', 'Huyện', 19, NULL, NULL),
(170, 'Huyện Võ Nhai', 'Huyện', 19, NULL, NULL),
(171, 'Huyện Đại Từ', 'Huyện', 19, NULL, NULL),
(172, 'Thị xã Phổ Yên', 'Thị xã', 19, NULL, NULL),
(173, 'Huyện Phú Bình', 'Huyện', 19, NULL, NULL),
(178, 'Thành phố Lạng Sơn', 'Thành phố', 20, NULL, NULL),
(180, 'Huyện Tràng Định', 'Huyện', 20, NULL, NULL),
(181, 'Huyện Bình Gia', 'Huyện', 20, NULL, NULL),
(182, 'Huyện Văn Lãng', 'Huyện', 20, NULL, NULL),
(183, 'Huyện Cao Lộc', 'Huyện', 20, NULL, NULL),
(184, 'Huyện Văn Quan', 'Huyện', 20, NULL, NULL),
(185, 'Huyện Bắc Sơn', 'Huyện', 20, NULL, NULL),
(186, 'Huyện Hữu Lũng', 'Huyện', 20, NULL, NULL),
(187, 'Huyện Chi Lăng', 'Huyện', 20, NULL, NULL),
(188, 'Huyện Lộc Bình', 'Huyện', 20, NULL, NULL),
(189, 'Huyện Đình Lập', 'Huyện', 20, NULL, NULL),
(193, 'Thành phố Hạ Long', 'Thành phố', 22, NULL, NULL),
(194, 'Thành phố Móng Cái', 'Thành phố', 22, NULL, NULL),
(195, 'Thành phố Cẩm Phả', 'Thành phố', 22, NULL, NULL),
(196, 'Thành phố Uông Bí', 'Thành phố', 22, NULL, NULL),
(198, 'Huyện Bình Liêu', 'Huyện', 22, NULL, NULL),
(199, 'Huyện Tiên Yên', 'Huyện', 22, NULL, NULL),
(200, 'Huyện Đầm Hà', 'Huyện', 22, NULL, NULL),
(201, 'Huyện Hải Hà', 'Huyện', 22, NULL, NULL),
(202, 'Huyện Ba Chẽ', 'Huyện', 22, NULL, NULL),
(203, 'Huyện Vân Đồn', 'Huyện', 22, NULL, NULL),
(204, 'Huyện Hoành Bồ', 'Huyện', 22, NULL, NULL),
(205, 'Thị xã Đông Triều', 'Thị xã', 22, NULL, NULL),
(206, 'Thị xã Quảng Yên', 'Thị xã', 22, NULL, NULL),
(207, 'Huyện Cô Tô', 'Huyện', 22, NULL, NULL),
(213, 'Thành phố Bắc Giang', 'Thành phố', 24, NULL, NULL),
(215, 'Huyện Yên Thế', 'Huyện', 24, NULL, NULL),
(216, 'Huyện Tân Yên', 'Huyện', 24, NULL, NULL),
(217, 'Huyện Lạng Giang', 'Huyện', 24, NULL, NULL),
(218, 'Huyện Lục Nam', 'Huyện', 24, NULL, NULL),
(219, 'Huyện Lục Ngạn', 'Huyện', 24, NULL, NULL),
(220, 'Huyện Sơn Động', 'Huyện', 24, NULL, NULL),
(221, 'Huyện Yên Dũng', 'Huyện', 24, NULL, NULL),
(222, 'Huyện Việt Yên', 'Huyện', 24, NULL, NULL),
(223, 'Huyện Hiệp Hòa', 'Huyện', 24, NULL, NULL),
(227, 'Thành phố Việt Trì', 'Thành phố', 25, NULL, NULL),
(228, 'Thị xã Phú Thọ', 'Thị xã', 25, NULL, NULL),
(230, 'Huyện Đoan Hùng', 'Huyện', 25, NULL, NULL),
(231, 'Huyện Hạ Hoà', 'Huyện', 25, NULL, NULL),
(232, 'Huyện Thanh Ba', 'Huyện', 25, NULL, NULL),
(233, 'Huyện Phù Ninh', 'Huyện', 25, NULL, NULL),
(234, 'Huyện Yên Lập', 'Huyện', 25, NULL, NULL),
(235, 'Huyện Cẩm Khê', 'Huyện', 25, NULL, NULL),
(236, 'Huyện Tam Nông', 'Huyện', 25, NULL, NULL),
(237, 'Huyện Lâm Thao', 'Huyện', 25, NULL, NULL),
(238, 'Huyện Thanh Sơn', 'Huyện', 25, NULL, NULL),
(239, 'Huyện Thanh Thuỷ', 'Huyện', 25, NULL, NULL),
(240, 'Huyện Tân Sơn', 'Huyện', 25, NULL, NULL),
(243, 'Thành phố Vĩnh Yên', 'Thành phố', 26, NULL, NULL),
(244, 'Thị xã Phúc Yên', 'Thị xã', 26, NULL, NULL),
(246, 'Huyện Lập Thạch', 'Huyện', 26, NULL, NULL),
(247, 'Huyện Tam Dương', 'Huyện', 26, NULL, NULL),
(248, 'Huyện Tam Đảo', 'Huyện', 26, NULL, NULL),
(249, 'Huyện Bình Xuyên', 'Huyện', 26, NULL, NULL),
(250, 'Huyện Mê Linh', 'Huyện', 1, NULL, NULL),
(251, 'Huyện Yên Lạc', 'Huyện', 26, NULL, NULL),
(252, 'Huyện Vĩnh Tường', 'Huyện', 26, NULL, NULL),
(253, 'Huyện Sông Lô', 'Huyện', 26, NULL, NULL),
(256, 'Thành phố Bắc Ninh', 'Thành phố', 27, NULL, NULL),
(258, 'Huyện Yên Phong', 'Huyện', 27, NULL, NULL),
(259, 'Huyện Quế Võ', 'Huyện', 27, NULL, NULL),
(260, 'Huyện Tiên Du', 'Huyện', 27, NULL, NULL),
(261, 'Thị xã Từ Sơn', 'Thị xã', 27, NULL, NULL),
(262, 'Huyện Thuận Thành', 'Huyện', 27, NULL, NULL),
(263, 'Huyện Gia Bình', 'Huyện', 27, NULL, NULL),
(264, 'Huyện Lương Tài', 'Huyện', 27, NULL, NULL),
(268, 'Quận Hà Đông', 'Quận', 1, NULL, NULL),
(269, 'Thị xã Sơn Tây', 'Thị xã', 1, NULL, NULL),
(271, 'Huyện Ba Vì', 'Huyện', 1, NULL, NULL),
(272, 'Huyện Phúc Thọ', 'Huyện', 1, NULL, NULL),
(273, 'Huyện Đan Phượng', 'Huyện', 1, NULL, NULL),
(274, 'Huyện Hoài Đức', 'Huyện', 1, NULL, NULL),
(275, 'Huyện Quốc Oai', 'Huyện', 1, NULL, NULL),
(276, 'Huyện Thạch Thất', 'Huyện', 1, NULL, NULL),
(277, 'Huyện Chương Mỹ', 'Huyện', 1, NULL, NULL),
(278, 'Huyện Thanh Oai', 'Huyện', 1, NULL, NULL),
(279, 'Huyện Thường Tín', 'Huyện', 1, NULL, NULL),
(280, 'Huyện Phú Xuyên', 'Huyện', 1, NULL, NULL),
(281, 'Huyện Ứng Hòa', 'Huyện', 1, NULL, NULL),
(282, 'Huyện Mỹ Đức', 'Huyện', 1, NULL, NULL),
(288, 'Thành phố Hải Dương', 'Thành phố', 30, NULL, NULL),
(290, 'Thị xã Chí Linh', 'Thị xã', 30, NULL, NULL),
(291, 'Huyện Nam Sách', 'Huyện', 30, NULL, NULL),
(292, 'Huyện Kinh Môn', 'Huyện', 30, NULL, NULL),
(293, 'Huyện Kim Thành', 'Huyện', 30, NULL, NULL),
(294, 'Huyện Thanh Hà', 'Huyện', 30, NULL, NULL),
(295, 'Huyện Cẩm Giàng', 'Huyện', 30, NULL, NULL),
(296, 'Huyện Bình Giang', 'Huyện', 30, NULL, NULL),
(297, 'Huyện Gia Lộc', 'Huyện', 30, NULL, NULL),
(298, 'Huyện Tứ Kỳ', 'Huyện', 30, NULL, NULL),
(299, 'Huyện Ninh Giang', 'Huyện', 30, NULL, NULL),
(300, 'Huyện Thanh Miện', 'Huyện', 30, NULL, NULL),
(303, 'Quận Hồng Bàng', 'Quận', 31, NULL, NULL),
(304, 'Quận Ngô Quyền', 'Quận', 31, NULL, NULL),
(305, 'Quận Lê Chân', 'Quận', 31, NULL, NULL),
(306, 'Quận Hải An', 'Quận', 31, NULL, NULL),
(307, 'Quận Kiến An', 'Quận', 31, NULL, NULL),
(308, 'Quận Đồ Sơn', 'Quận', 31, NULL, NULL),
(309, 'Quận Dương Kinh', 'Quận', 31, NULL, NULL),
(311, 'Huyện Thuỷ Nguyên', 'Huyện', 31, NULL, NULL),
(312, 'Huyện An Dương', 'Huyện', 31, NULL, NULL),
(313, 'Huyện An Lão', 'Huyện', 31, NULL, NULL),
(314, 'Huyện Kiến Thuỵ', 'Huyện', 31, NULL, NULL),
(315, 'Huyện Tiên Lãng', 'Huyện', 31, NULL, NULL),
(316, 'Huyện Vĩnh Bảo', 'Huyện', 31, NULL, NULL),
(317, 'Huyện Cát Hải', 'Huyện', 31, NULL, NULL),
(323, 'Thành phố Hưng Yên', 'Thành phố', 33, NULL, NULL),
(325, 'Huyện Văn Lâm', 'Huyện', 33, NULL, NULL),
(326, 'Huyện Văn Giang', 'Huyện', 33, NULL, NULL),
(327, 'Huyện Yên Mỹ', 'Huyện', 33, NULL, NULL),
(328, 'Huyện Mỹ Hào', 'Huyện', 33, NULL, NULL),
(329, 'Huyện Ân Thi', 'Huyện', 33, NULL, NULL),
(330, 'Huyện Khoái Châu', 'Huyện', 33, NULL, NULL),
(331, 'Huyện Kim Động', 'Huyện', 33, NULL, NULL),
(332, 'Huyện Tiên Lữ', 'Huyện', 33, NULL, NULL),
(333, 'Huyện Phù Cừ', 'Huyện', 33, NULL, NULL),
(336, 'Thành phố Thái Bình', 'Thành phố', 34, NULL, NULL),
(338, 'Huyện Quỳnh Phụ', 'Huyện', 34, NULL, NULL),
(339, 'Huyện Hưng Hà', 'Huyện', 34, NULL, NULL),
(340, 'Huyện Đông Hưng', 'Huyện', 34, NULL, NULL),
(341, 'Huyện Thái Thụy', 'Huyện', 34, NULL, NULL),
(342, 'Huyện Tiền Hải', 'Huyện', 34, NULL, NULL),
(343, 'Huyện Kiến Xương', 'Huyện', 34, NULL, NULL),
(344, 'Huyện Vũ Thư', 'Huyện', 34, NULL, NULL),
(347, 'Thành phố Phủ Lý', 'Thành phố', 35, NULL, NULL),
(349, 'Huyện Duy Tiên', 'Huyện', 35, NULL, NULL),
(350, 'Huyện Kim Bảng', 'Huyện', 35, NULL, NULL),
(351, 'Huyện Thanh Liêm', 'Huyện', 35, NULL, NULL),
(352, 'Huyện Bình Lục', 'Huyện', 35, NULL, NULL),
(353, 'Huyện Lý Nhân', 'Huyện', 35, NULL, NULL),
(356, 'Thành phố Nam Định', 'Thành phố', 36, NULL, NULL),
(358, 'Huyện Mỹ Lộc', 'Huyện', 36, NULL, NULL),
(359, 'Huyện Vụ Bản', 'Huyện', 36, NULL, NULL),
(360, 'Huyện Ý Yên', 'Huyện', 36, NULL, NULL),
(361, 'Huyện Nghĩa Hưng', 'Huyện', 36, NULL, NULL),
(362, 'Huyện Nam Trực', 'Huyện', 36, NULL, NULL),
(363, 'Huyện Trực Ninh', 'Huyện', 36, NULL, NULL),
(364, 'Huyện Xuân Trường', 'Huyện', 36, NULL, NULL),
(365, 'Huyện Giao Thủy', 'Huyện', 36, NULL, NULL),
(366, 'Huyện Hải Hậu', 'Huyện', 36, NULL, NULL),
(369, 'Thành phố Ninh Bình', 'Thành phố', 37, NULL, NULL),
(370, 'Thành phố Tam Điệp', 'Thành phố', 37, NULL, NULL),
(372, 'Huyện Nho Quan', 'Huyện', 37, NULL, NULL),
(373, 'Huyện Gia Viễn', 'Huyện', 37, NULL, NULL),
(374, 'Huyện Hoa Lư', 'Huyện', 37, NULL, NULL),
(375, 'Huyện Yên Khánh', 'Huyện', 37, NULL, NULL),
(376, 'Huyện Kim Sơn', 'Huyện', 37, NULL, NULL),
(377, 'Huyện Yên Mô', 'Huyện', 37, NULL, NULL),
(380, 'Thành phố Thanh Hóa', 'Thành phố', 38, NULL, NULL),
(381, 'Thị xã Bỉm Sơn', 'Thị xã', 38, NULL, NULL),
(382, 'Thành phố Sầm Sơn', 'Thành phố', 38, NULL, NULL),
(384, 'Huyện Mường Lát', 'Huyện', 38, NULL, NULL),
(385, 'Huyện Quan Hóa', 'Huyện', 38, NULL, NULL),
(386, 'Huyện Bá Thước', 'Huyện', 38, NULL, NULL),
(387, 'Huyện Quan Sơn', 'Huyện', 38, NULL, NULL),
(388, 'Huyện Lang Chánh', 'Huyện', 38, NULL, NULL),
(389, 'Huyện Ngọc Lặc', 'Huyện', 38, NULL, NULL),
(390, 'Huyện Cẩm Thủy', 'Huyện', 38, NULL, NULL),
(391, 'Huyện Thạch Thành', 'Huyện', 38, NULL, NULL),
(392, 'Huyện Hà Trung', 'Huyện', 38, NULL, NULL),
(393, 'Huyện Vĩnh Lộc', 'Huyện', 38, NULL, NULL),
(394, 'Huyện Yên Định', 'Huyện', 38, NULL, NULL),
(395, 'Huyện Thọ Xuân', 'Huyện', 38, NULL, NULL),
(396, 'Huyện Thường Xuân', 'Huyện', 38, NULL, NULL),
(397, 'Huyện Triệu Sơn', 'Huyện', 38, NULL, NULL),
(398, 'Huyện Thiệu Hóa', 'Huyện', 38, NULL, NULL),
(399, 'Huyện Hoằng Hóa', 'Huyện', 38, NULL, NULL),
(400, 'Huyện Hậu Lộc', 'Huyện', 38, NULL, NULL),
(401, 'Huyện Nga Sơn', 'Huyện', 38, NULL, NULL),
(402, 'Huyện Như Xuân', 'Huyện', 38, NULL, NULL),
(403, 'Huyện Như Thanh', 'Huyện', 38, NULL, NULL),
(404, 'Huyện Nông Cống', 'Huyện', 38, NULL, NULL),
(405, 'Huyện Đông Sơn', 'Huyện', 38, NULL, NULL),
(406, 'Huyện Quảng Xương', 'Huyện', 38, NULL, NULL),
(407, 'Huyện Tĩnh Gia', 'Huyện', 38, NULL, NULL),
(412, 'Thành phố Vinh', 'Thành phố', 40, NULL, NULL),
(413, 'Thị xã Cửa Lò', 'Thị xã', 40, NULL, NULL),
(414, 'Thị xã Thái Hoà', 'Thị xã', 40, NULL, NULL),
(415, 'Huyện Quế Phong', 'Huyện', 40, NULL, NULL),
(416, 'Huyện Quỳ Châu', 'Huyện', 40, NULL, NULL),
(417, 'Huyện Kỳ Sơn', 'Huyện', 40, NULL, NULL),
(418, 'Huyện Tương Dương', 'Huyện', 40, NULL, NULL),
(419, 'Huyện Nghĩa Đàn', 'Huyện', 40, NULL, NULL),
(420, 'Huyện Quỳ Hợp', 'Huyện', 40, NULL, NULL),
(421, 'Huyện Quỳnh Lưu', 'Huyện', 40, NULL, NULL),
(422, 'Huyện Con Cuông', 'Huyện', 40, NULL, NULL),
(423, 'Huyện Tân Kỳ', 'Huyện', 40, NULL, NULL),
(424, 'Huyện Anh Sơn', 'Huyện', 40, NULL, NULL),
(425, 'Huyện Diễn Châu', 'Huyện', 40, NULL, NULL),
(426, 'Huyện Yên Thành', 'Huyện', 40, NULL, NULL),
(427, 'Huyện Đô Lương', 'Huyện', 40, NULL, NULL),
(428, 'Huyện Thanh Chương', 'Huyện', 40, NULL, NULL),
(429, 'Huyện Nghi Lộc', 'Huyện', 40, NULL, NULL),
(430, 'Huyện Nam Đàn', 'Huyện', 40, NULL, NULL),
(431, 'Huyện Hưng Nguyên', 'Huyện', 40, NULL, NULL),
(432, 'Thị xã Hoàng Mai', 'Thị xã', 40, NULL, NULL),
(436, 'Thành phố Hà Tĩnh', 'Thành phố', 42, NULL, NULL),
(437, 'Thị xã Hồng Lĩnh', 'Thị xã', 42, NULL, NULL),
(439, 'Huyện Hương Sơn', 'Huyện', 42, NULL, NULL),
(440, 'Huyện Đức Thọ', 'Huyện', 42, NULL, NULL),
(441, 'Huyện Vũ Quang', 'Huyện', 42, NULL, NULL),
(442, 'Huyện Nghi Xuân', 'Huyện', 42, NULL, NULL),
(443, 'Huyện Can Lộc', 'Huyện', 42, NULL, NULL),
(444, 'Huyện Hương Khê', 'Huyện', 42, NULL, NULL),
(445, 'Huyện Thạch Hà', 'Huyện', 42, NULL, NULL),
(446, 'Huyện Cẩm Xuyên', 'Huyện', 42, NULL, NULL),
(447, 'Huyện Kỳ Anh', 'Huyện', 42, NULL, NULL),
(448, 'Huyện Lộc Hà', 'Huyện', 42, NULL, NULL),
(449, 'Thị xã Kỳ Anh', 'Thị xã', 42, NULL, NULL),
(450, 'Thành Phố Đồng Hới', 'Thành phố', 44, NULL, NULL),
(452, 'Huyện Minh Hóa', 'Huyện', 44, NULL, NULL),
(453, 'Huyện Tuyên Hóa', 'Huyện', 44, NULL, NULL),
(454, 'Huyện Quảng Trạch', 'Huyện', 44, NULL, NULL),
(455, 'Huyện Bố Trạch', 'Huyện', 44, NULL, NULL),
(456, 'Huyện Quảng Ninh', 'Huyện', 44, NULL, NULL),
(457, 'Huyện Lệ Thủy', 'Huyện', 44, NULL, NULL),
(458, 'Thị xã Ba Đồn', 'Thị xã', 44, NULL, NULL),
(461, 'Thành phố Đông Hà', 'Thành phố', 45, NULL, NULL),
(462, 'Thị xã Quảng Trị', 'Thị xã', 45, NULL, NULL),
(464, 'Huyện Vĩnh Linh', 'Huyện', 45, NULL, NULL),
(465, 'Huyện Hướng Hóa', 'Huyện', 45, NULL, NULL),
(466, 'Huyện Gio Linh', 'Huyện', 45, NULL, NULL),
(467, 'Huyện Đa Krông', 'Huyện', 45, NULL, NULL),
(468, 'Huyện Cam Lộ', 'Huyện', 45, NULL, NULL),
(469, 'Huyện Triệu Phong', 'Huyện', 45, NULL, NULL),
(470, 'Huyện Hải Lăng', 'Huyện', 45, NULL, NULL),
(474, 'Thành phố Huế', 'Thành phố', 46, NULL, NULL),
(476, 'Huyện Phong Điền', 'Huyện', 46, NULL, NULL),
(477, 'Huyện Quảng Điền', 'Huyện', 46, NULL, NULL),
(478, 'Huyện Phú Vang', 'Huyện', 46, NULL, NULL),
(479, 'Thị xã Hương Thủy', 'Thị xã', 46, NULL, NULL),
(480, 'Thị xã Hương Trà', 'Thị xã', 46, NULL, NULL),
(481, 'Huyện A Lưới', 'Huyện', 46, NULL, NULL),
(482, 'Huyện Phú Lộc', 'Huyện', 46, NULL, NULL),
(483, 'Huyện Nam Đông', 'Huyện', 46, NULL, NULL),
(490, 'Quận Liên Chiểu', 'Quận', 48, NULL, NULL),
(491, 'Quận Thanh Khê', 'Quận', 48, NULL, NULL),
(492, 'Quận Hải Châu', 'Quận', 48, NULL, NULL),
(493, 'Quận Sơn Trà', 'Quận', 48, NULL, NULL),
(494, 'Quận Ngũ Hành Sơn', 'Quận', 48, NULL, NULL),
(495, 'Quận Cẩm Lệ', 'Quận', 48, NULL, NULL),
(497, 'Huyện Hòa Vang', 'Huyện', 48, NULL, NULL),
(502, 'Thành phố Tam Kỳ', 'Thành phố', 49, NULL, NULL),
(503, 'Thành phố Hội An', 'Thành phố', 49, NULL, NULL),
(504, 'Huyện Tây Giang', 'Huyện', 49, NULL, NULL),
(505, 'Huyện Đông Giang', 'Huyện', 49, NULL, NULL),
(506, 'Huyện Đại Lộc', 'Huyện', 49, NULL, NULL),
(507, 'Thị xã Điện Bàn', 'Thị xã', 49, NULL, NULL),
(508, 'Huyện Duy Xuyên', 'Huyện', 49, NULL, NULL),
(509, 'Huyện Quế Sơn', 'Huyện', 49, NULL, NULL),
(510, 'Huyện Nam Giang', 'Huyện', 49, NULL, NULL),
(511, 'Huyện Phước Sơn', 'Huyện', 49, NULL, NULL),
(512, 'Huyện Hiệp Đức', 'Huyện', 49, NULL, NULL),
(513, 'Huyện Thăng Bình', 'Huyện', 49, NULL, NULL),
(514, 'Huyện Tiên Phước', 'Huyện', 49, NULL, NULL),
(515, 'Huyện Bắc Trà My', 'Huyện', 49, NULL, NULL),
(516, 'Huyện Nam Trà My', 'Huyện', 49, NULL, NULL),
(517, 'Huyện Núi Thành', 'Huyện', 49, NULL, NULL),
(518, 'Huyện Phú Ninh', 'Huyện', 49, NULL, NULL),
(519, 'Huyện Nông Sơn', 'Huyện', 49, NULL, NULL),
(522, 'Thành phố Quảng Ngãi', 'Thành phố', 51, NULL, NULL),
(524, 'Huyện Bình Sơn', 'Huyện', 51, NULL, NULL),
(525, 'Huyện Trà Bồng', 'Huyện', 51, NULL, NULL),
(526, 'Huyện Tây Trà', 'Huyện', 51, NULL, NULL),
(527, 'Huyện Sơn Tịnh', 'Huyện', 51, NULL, NULL),
(528, 'Huyện Tư Nghĩa', 'Huyện', 51, NULL, NULL),
(529, 'Huyện Sơn Hà', 'Huyện', 51, NULL, NULL),
(530, 'Huyện Sơn Tây', 'Huyện', 51, NULL, NULL),
(531, 'Huyện Minh Long', 'Huyện', 51, NULL, NULL),
(532, 'Huyện Nghĩa Hành', 'Huyện', 51, NULL, NULL),
(533, 'Huyện Mộ Đức', 'Huyện', 51, NULL, NULL),
(534, 'Huyện Đức Phổ', 'Huyện', 51, NULL, NULL),
(535, 'Huyện Ba Tơ', 'Huyện', 51, NULL, NULL),
(536, 'Huyện Lý Sơn', 'Huyện', 51, NULL, NULL),
(540, 'Thành phố Qui Nhơn', 'Thành phố', 52, NULL, NULL),
(542, 'Huyện An Lão', 'Huyện', 52, NULL, NULL),
(543, 'Huyện Hoài Nhơn', 'Huyện', 52, NULL, NULL),
(544, 'Huyện Hoài Ân', 'Huyện', 52, NULL, NULL),
(545, 'Huyện Phù Mỹ', 'Huyện', 52, NULL, NULL),
(546, 'Huyện Vĩnh Thạnh', 'Huyện', 52, NULL, NULL),
(547, 'Huyện Tây Sơn', 'Huyện', 52, NULL, NULL),
(548, 'Huyện Phù Cát', 'Huyện', 52, NULL, NULL),
(549, 'Thị xã An Nhơn', 'Thị xã', 52, NULL, NULL),
(550, 'Huyện Tuy Phước', 'Huyện', 52, NULL, NULL),
(551, 'Huyện Vân Canh', 'Huyện', 52, NULL, NULL),
(555, 'Thành phố Tuy Hoà', 'Thành phố', 54, NULL, NULL),
(557, 'Thị xã Sông Cầu', 'Thị xã', 54, NULL, NULL),
(558, 'Huyện Đồng Xuân', 'Huyện', 54, NULL, NULL),
(559, 'Huyện Tuy An', 'Huyện', 54, NULL, NULL),
(560, 'Huyện Sơn Hòa', 'Huyện', 54, NULL, NULL),
(561, 'Huyện Sông Hinh', 'Huyện', 54, NULL, NULL),
(562, 'Huyện Tây Hoà', 'Huyện', 54, NULL, NULL),
(563, 'Huyện Phú Hoà', 'Huyện', 54, NULL, NULL),
(564, 'Huyện Đông Hòa', 'Huyện', 54, NULL, NULL),
(568, 'Thành phố Nha Trang', 'Thành phố', 56, NULL, NULL),
(569, 'Thành phố Cam Ranh', 'Thành phố', 56, NULL, NULL),
(570, 'Huyện Cam Lâm', 'Huyện', 56, NULL, NULL),
(571, 'Huyện Vạn Ninh', 'Huyện', 56, NULL, NULL),
(572, 'Thị xã Ninh Hòa', 'Thị xã', 56, NULL, NULL),
(573, 'Huyện Khánh Vĩnh', 'Huyện', 56, NULL, NULL),
(574, 'Huyện Diên Khánh', 'Huyện', 56, NULL, NULL),
(575, 'Huyện Khánh Sơn', 'Huyện', 56, NULL, NULL),
(576, 'Huyện Trường Sa', 'Huyện', 56, NULL, NULL),
(582, 'Thành phố Phan Rang-Tháp Chàm', 'Thành phố', 58, NULL, NULL),
(584, 'Huyện Bác Ái', 'Huyện', 58, NULL, NULL),
(585, 'Huyện Ninh Sơn', 'Huyện', 58, NULL, NULL),
(586, 'Huyện Ninh Hải', 'Huyện', 58, NULL, NULL),
(587, 'Huyện Ninh Phước', 'Huyện', 58, NULL, NULL),
(588, 'Huyện Thuận Bắc', 'Huyện', 58, NULL, NULL),
(589, 'Huyện Thuận Nam', 'Huyện', 58, NULL, NULL),
(593, 'Thành phố Phan Thiết', 'Thành phố', 60, NULL, NULL),
(594, 'Thị xã La Gi', 'Thị xã', 60, NULL, NULL),
(595, 'Huyện Tuy Phong', 'Huyện', 60, NULL, NULL),
(596, 'Huyện Bắc Bình', 'Huyện', 60, NULL, NULL),
(597, 'Huyện Hàm Thuận Bắc', 'Huyện', 60, NULL, NULL),
(598, 'Huyện Hàm Thuận Nam', 'Huyện', 60, NULL, NULL),
(599, 'Huyện Tánh Linh', 'Huyện', 60, NULL, NULL),
(600, 'Huyện Đức Linh', 'Huyện', 60, NULL, NULL),
(601, 'Huyện Hàm Tân', 'Huyện', 60, NULL, NULL),
(602, 'Huyện Phú Quí', 'Huyện', 60, NULL, NULL),
(608, 'Thành phố Kon Tum', 'Thành phố', 62, NULL, NULL),
(610, 'Huyện Đắk Glei', 'Huyện', 62, NULL, NULL),
(611, 'Huyện Ngọc Hồi', 'Huyện', 62, NULL, NULL),
(612, 'Huyện Đắk Tô', 'Huyện', 62, NULL, NULL),
(613, 'Huyện Kon Plông', 'Huyện', 62, NULL, NULL),
(614, 'Huyện Kon Rẫy', 'Huyện', 62, NULL, NULL),
(615, 'Huyện Đắk Hà', 'Huyện', 62, NULL, NULL),
(616, 'Huyện Sa Thầy', 'Huyện', 62, NULL, NULL),
(617, 'Huyện Tu Mơ Rông', 'Huyện', 62, NULL, NULL),
(618, 'Huyện Ia H\' Drai', 'Huyện', 62, NULL, NULL),
(622, 'Thành phố Pleiku', 'Thành phố', 64, NULL, NULL),
(623, 'Thị xã An Khê', 'Thị xã', 64, NULL, NULL),
(624, 'Thị xã Ayun Pa', 'Thị xã', 64, NULL, NULL),
(625, 'Huyện KBang', 'Huyện', 64, NULL, NULL),
(626, 'Huyện Đăk Đoa', 'Huyện', 64, NULL, NULL),
(627, 'Huyện Chư Păh', 'Huyện', 64, NULL, NULL),
(628, 'Huyện Ia Grai', 'Huyện', 64, NULL, NULL),
(629, 'Huyện Mang Yang', 'Huyện', 64, NULL, NULL),
(630, 'Huyện Kông Chro', 'Huyện', 64, NULL, NULL),
(631, 'Huyện Đức Cơ', 'Huyện', 64, NULL, NULL),
(632, 'Huyện Chư Prông', 'Huyện', 64, NULL, NULL),
(633, 'Huyện Chư Sê', 'Huyện', 64, NULL, NULL),
(634, 'Huyện Đăk Pơ', 'Huyện', 64, NULL, NULL),
(635, 'Huyện Ia Pa', 'Huyện', 64, NULL, NULL),
(637, 'Huyện Krông Pa', 'Huyện', 64, NULL, NULL),
(638, 'Huyện Phú Thiện', 'Huyện', 64, NULL, NULL),
(639, 'Huyện Chư Pưh', 'Huyện', 64, NULL, NULL),
(643, 'Thành phố Buôn Ma Thuột', 'Thành phố', 66, NULL, NULL),
(644, 'Thị Xã Buôn Hồ', 'Thị xã', 66, NULL, NULL),
(645, 'Huyện Ea H\'leo', 'Huyện', 66, NULL, NULL),
(646, 'Huyện Ea Súp', 'Huyện', 66, NULL, NULL),
(647, 'Huyện Buôn Đôn', 'Huyện', 66, NULL, NULL),
(648, 'Huyện Cư M\'gar', 'Huyện', 66, NULL, NULL),
(649, 'Huyện Krông Búk', 'Huyện', 66, NULL, NULL),
(650, 'Huyện Krông Năng', 'Huyện', 66, NULL, NULL),
(651, 'Huyện Ea Kar', 'Huyện', 66, NULL, NULL),
(652, 'Huyện M\'Đrắk', 'Huyện', 66, NULL, NULL),
(653, 'Huyện Krông Bông', 'Huyện', 66, NULL, NULL),
(654, 'Huyện Krông Pắc', 'Huyện', 66, NULL, NULL),
(655, 'Huyện Krông A Na', 'Huyện', 66, NULL, NULL),
(656, 'Huyện Lắk', 'Huyện', 66, NULL, NULL),
(657, 'Huyện Cư Kuin', 'Huyện', 66, NULL, NULL),
(660, 'Thị xã Gia Nghĩa', 'Thị xã', 67, NULL, NULL),
(661, 'Huyện Đăk Glong', 'Huyện', 67, NULL, NULL),
(662, 'Huyện Cư Jút', 'Huyện', 67, NULL, NULL),
(663, 'Huyện Đắk Mil', 'Huyện', 67, NULL, NULL),
(664, 'Huyện Krông Nô', 'Huyện', 67, NULL, NULL),
(665, 'Huyện Đắk Song', 'Huyện', 67, NULL, NULL),
(666, 'Huyện Đắk R\'Lấp', 'Huyện', 67, NULL, NULL),
(667, 'Huyện Tuy Đức', 'Huyện', 67, NULL, NULL),
(672, 'Thành phố Đà Lạt', 'Thành phố', 68, NULL, NULL),
(673, 'Thành phố Bảo Lộc', 'Thành phố', 68, NULL, NULL),
(674, 'Huyện Đam Rông', 'Huyện', 68, NULL, NULL),
(675, 'Huyện Lạc Dương', 'Huyện', 68, NULL, NULL),
(676, 'Huyện Lâm Hà', 'Huyện', 68, NULL, NULL),
(677, 'Huyện Đơn Dương', 'Huyện', 68, NULL, NULL),
(678, 'Huyện Đức Trọng', 'Huyện', 68, NULL, NULL),
(679, 'Huyện Di Linh', 'Huyện', 68, NULL, NULL),
(680, 'Huyện Bảo Lâm', 'Huyện', 68, NULL, NULL),
(681, 'Huyện Đạ Huoai', 'Huyện', 68, NULL, NULL),
(682, 'Huyện Đạ Tẻh', 'Huyện', 68, NULL, NULL),
(683, 'Huyện Cát Tiên', 'Huyện', 68, NULL, NULL),
(688, 'Thị xã Phước Long', 'Thị xã', 70, NULL, NULL),
(689, 'Thị xã Đồng Xoài', 'Thị xã', 70, NULL, NULL),
(690, 'Thị xã Bình Long', 'Thị xã', 70, NULL, NULL),
(691, 'Huyện Bù Gia Mập', 'Huyện', 70, NULL, NULL),
(692, 'Huyện Lộc Ninh', 'Huyện', 70, NULL, NULL),
(693, 'Huyện Bù Đốp', 'Huyện', 70, NULL, NULL),
(694, 'Huyện Hớn Quản', 'Huyện', 70, NULL, NULL),
(695, 'Huyện Đồng Phú', 'Huyện', 70, NULL, NULL),
(696, 'Huyện Bù Đăng', 'Huyện', 70, NULL, NULL),
(697, 'Huyện Chơn Thành', 'Huyện', 70, NULL, NULL),
(698, 'Huyện Phú Riềng', 'Huyện', 70, NULL, NULL),
(703, 'Thành phố Tây Ninh', 'Thành phố', 72, NULL, NULL),
(705, 'Huyện Tân Biên', 'Huyện', 72, NULL, NULL),
(706, 'Huyện Tân Châu', 'Huyện', 72, NULL, NULL),
(707, 'Huyện Dương Minh Châu', 'Huyện', 72, NULL, NULL),
(708, 'Huyện Châu Thành', 'Huyện', 72, NULL, NULL),
(709, 'Huyện Hòa Thành', 'Huyện', 72, NULL, NULL),
(710, 'Huyện Gò Dầu', 'Huyện', 72, NULL, NULL),
(711, 'Huyện Bến Cầu', 'Huyện', 72, NULL, NULL),
(712, 'Huyện Trảng Bàng', 'Huyện', 72, NULL, NULL),
(718, 'Thành phố Thủ Dầu Một', 'Thành phố', 74, NULL, NULL),
(719, 'Huyện Bàu Bàng', 'Huyện', 74, NULL, NULL),
(720, 'Huyện Dầu Tiếng', 'Huyện', 74, NULL, NULL),
(721, 'Thị xã Bến Cát', 'Thị xã', 74, NULL, NULL),
(722, 'Huyện Phú Giáo', 'Huyện', 74, NULL, NULL),
(723, 'Thị xã Tân Uyên', 'Thị xã', 74, NULL, NULL),
(724, 'Thị xã Dĩ An', 'Thị xã', 74, NULL, NULL),
(725, 'Thị xã Thuận An', 'Thị xã', 74, NULL, NULL),
(726, 'Huyện Bắc Tân Uyên', 'Huyện', 74, NULL, NULL),
(731, 'Thành phố Biên Hòa', 'Thành phố', 75, NULL, NULL),
(732, 'Thị xã Long Khánh', 'Thị xã', 75, NULL, NULL),
(734, 'Huyện Tân Phú', 'Huyện', 75, NULL, NULL),
(735, 'Huyện Vĩnh Cửu', 'Huyện', 75, NULL, NULL),
(736, 'Huyện Định Quán', 'Huyện', 75, NULL, NULL),
(737, 'Huyện Trảng Bom', 'Huyện', 75, NULL, NULL),
(738, 'Huyện Thống Nhất', 'Huyện', 75, NULL, NULL),
(739, 'Huyện Cẩm Mỹ', 'Huyện', 75, NULL, NULL),
(740, 'Huyện Long Thành', 'Huyện', 75, NULL, NULL),
(741, 'Huyện Xuân Lộc', 'Huyện', 75, NULL, NULL),
(742, 'Huyện Nhơn Trạch', 'Huyện', 75, NULL, NULL),
(747, 'Thành phố Vũng Tàu', 'Thành phố', 77, NULL, NULL),
(748, 'Thành phố Bà Rịa', 'Thành phố', 77, NULL, NULL),
(750, 'Huyện Châu Đức', 'Huyện', 77, NULL, NULL),
(751, 'Huyện Xuyên Mộc', 'Huyện', 77, NULL, NULL),
(752, 'Huyện Long Điền', 'Huyện', 77, NULL, NULL),
(753, 'Huyện Đất Đỏ', 'Huyện', 77, NULL, NULL),
(754, 'Huyện Tân Thành', 'Huyện', 77, NULL, NULL),
(760, 'Quận 1', 'Quận', 79, NULL, NULL),
(761, 'Quận 12', 'Quận', 79, NULL, NULL),
(762, 'Quận Thủ Đức', 'Quận', 79, NULL, NULL),
(763, 'Quận 9', 'Quận', 79, NULL, NULL),
(764, 'Quận Gò Vấp', 'Quận', 79, NULL, NULL),
(765, 'Quận Bình Thạnh', 'Quận', 79, NULL, NULL),
(766, 'Quận Tân Bình', 'Quận', 79, NULL, NULL),
(767, 'Quận Tân Phú', 'Quận', 79, NULL, NULL),
(768, 'Quận Phú Nhuận', 'Quận', 79, NULL, NULL),
(769, 'Quận 2', 'Quận', 79, NULL, NULL),
(770, 'Quận 3', 'Quận', 79, NULL, NULL),
(771, 'Quận 10', 'Quận', 79, NULL, NULL),
(772, 'Quận 11', 'Quận', 79, NULL, NULL),
(773, 'Quận 4', 'Quận', 79, NULL, NULL),
(774, 'Quận 5', 'Quận', 79, NULL, NULL),
(775, 'Quận 6', 'Quận', 79, NULL, NULL),
(776, 'Quận 8', 'Quận', 79, NULL, NULL),
(777, 'Quận Bình Tân', 'Quận', 79, NULL, NULL),
(778, 'Quận 7', 'Quận', 79, NULL, NULL),
(783, 'Huyện Củ Chi', 'Huyện', 79, NULL, NULL),
(784, 'Huyện Hóc Môn', 'Huyện', 79, NULL, NULL),
(785, 'Huyện Bình Chánh', 'Huyện', 79, NULL, NULL),
(786, 'Huyện Nhà Bè', 'Huyện', 79, NULL, NULL),
(787, 'Huyện Cần Giờ', 'Huyện', 79, NULL, NULL),
(794, 'Thành phố Tân An', 'Thành phố', 80, NULL, NULL),
(795, 'Thị xã Kiến Tường', 'Thị xã', 80, NULL, NULL),
(796, 'Huyện Tân Hưng', 'Huyện', 80, NULL, NULL),
(797, 'Huyện Vĩnh Hưng', 'Huyện', 80, NULL, NULL),
(798, 'Huyện Mộc Hóa', 'Huyện', 80, NULL, NULL),
(799, 'Huyện Tân Thạnh', 'Huyện', 80, NULL, NULL),
(800, 'Huyện Thạnh Hóa', 'Huyện', 80, NULL, NULL),
(801, 'Huyện Đức Huệ', 'Huyện', 80, NULL, NULL),
(802, 'Huyện Đức Hòa', 'Huyện', 80, NULL, NULL),
(803, 'Huyện Bến Lức', 'Huyện', 80, NULL, NULL),
(804, 'Huyện Thủ Thừa', 'Huyện', 80, NULL, NULL),
(805, 'Huyện Tân Trụ', 'Huyện', 80, NULL, NULL),
(806, 'Huyện Cần Đước', 'Huyện', 80, NULL, NULL),
(807, 'Huyện Cần Giuộc', 'Huyện', 80, NULL, NULL),
(808, 'Huyện Châu Thành', 'Huyện', 80, NULL, NULL),
(815, 'Thành phố Mỹ Tho', 'Thành phố', 82, NULL, NULL),
(816, 'Thị xã Gò Công', 'Thị xã', 82, NULL, NULL),
(817, 'Thị xã Cai Lậy', 'Thị xã', 82, NULL, NULL),
(818, 'Huyện Tân Phước', 'Huyện', 82, NULL, NULL),
(819, 'Huyện Cái Bè', 'Huyện', 82, NULL, NULL),
(820, 'Huyện Cai Lậy', 'Huyện', 82, NULL, NULL),
(821, 'Huyện Châu Thành', 'Huyện', 82, NULL, NULL),
(822, 'Huyện Chợ Gạo', 'Huyện', 82, NULL, NULL),
(823, 'Huyện Gò Công Tây', 'Huyện', 82, NULL, NULL),
(824, 'Huyện Gò Công Đông', 'Huyện', 82, NULL, NULL),
(825, 'Huyện Tân Phú Đông', 'Huyện', 82, NULL, NULL),
(829, 'Thành phố Bến Tre', 'Thành phố', 83, NULL, NULL),
(831, 'Huyện Châu Thành', 'Huyện', 83, NULL, NULL),
(832, 'Huyện Chợ Lách', 'Huyện', 83, NULL, NULL),
(833, 'Huyện Mỏ Cày Nam', 'Huyện', 83, NULL, NULL),
(834, 'Huyện Giồng Trôm', 'Huyện', 83, NULL, NULL),
(835, 'Huyện Bình Đại', 'Huyện', 83, NULL, NULL),
(836, 'Huyện Ba Tri', 'Huyện', 83, NULL, NULL),
(837, 'Huyện Thạnh Phú', 'Huyện', 83, NULL, NULL),
(838, 'Huyện Mỏ Cày Bắc', 'Huyện', 83, NULL, NULL),
(842, 'Thành phố Trà Vinh', 'Thành phố', 84, NULL, NULL),
(844, 'Huyện Càng Long', 'Huyện', 84, NULL, NULL),
(845, 'Huyện Cầu Kè', 'Huyện', 84, NULL, NULL),
(846, 'Huyện Tiểu Cần', 'Huyện', 84, NULL, NULL),
(847, 'Huyện Châu Thành', 'Huyện', 84, NULL, NULL),
(848, 'Huyện Cầu Ngang', 'Huyện', 84, NULL, NULL),
(849, 'Huyện Trà Cú', 'Huyện', 84, NULL, NULL),
(850, 'Huyện Duyên Hải', 'Huyện', 84, NULL, NULL),
(851, 'Thị xã Duyên Hải', 'Thị xã', 84, NULL, NULL),
(855, 'Thành phố Vĩnh Long', 'Thành phố', 86, NULL, NULL),
(857, 'Huyện Long Hồ', 'Huyện', 86, NULL, NULL),
(858, 'Huyện Mang Thít', 'Huyện', 86, NULL, NULL),
(859, 'Huyện  Vũng Liêm', 'Huyện', 86, NULL, NULL),
(860, 'Huyện Tam Bình', 'Huyện', 86, NULL, NULL),
(861, 'Thị xã Bình Minh', 'Thị xã', 86, NULL, NULL),
(862, 'Huyện Trà Ôn', 'Huyện', 86, NULL, NULL),
(863, 'Huyện Bình Tân', 'Huyện', 86, NULL, NULL),
(866, 'Thành phố Cao Lãnh', 'Thành phố', 87, NULL, NULL),
(867, 'Thành phố Sa Đéc', 'Thành phố', 87, NULL, NULL),
(868, 'Thị xã Hồng Ngự', 'Thị xã', 87, NULL, NULL),
(869, 'Huyện Tân Hồng', 'Huyện', 87, NULL, NULL),
(870, 'Huyện Hồng Ngự', 'Huyện', 87, NULL, NULL),
(871, 'Huyện Tam Nông', 'Huyện', 87, NULL, NULL),
(872, 'Huyện Tháp Mười', 'Huyện', 87, NULL, NULL),
(873, 'Huyện Cao Lãnh', 'Huyện', 87, NULL, NULL),
(874, 'Huyện Thanh Bình', 'Huyện', 87, NULL, NULL),
(875, 'Huyện Lấp Vò', 'Huyện', 87, NULL, NULL),
(876, 'Huyện Lai Vung', 'Huyện', 87, NULL, NULL),
(877, 'Huyện Châu Thành', 'Huyện', 87, NULL, NULL),
(883, 'Thành phố Long Xuyên', 'Thành phố', 89, NULL, NULL),
(884, 'Thành phố Châu Đốc', 'Thành phố', 89, NULL, NULL),
(886, 'Huyện An Phú', 'Huyện', 89, NULL, NULL),
(887, 'Thị xã Tân Châu', 'Thị xã', 89, NULL, NULL),
(888, 'Huyện Phú Tân', 'Huyện', 89, NULL, NULL),
(889, 'Huyện Châu Phú', 'Huyện', 89, NULL, NULL),
(890, 'Huyện Tịnh Biên', 'Huyện', 89, NULL, NULL),
(891, 'Huyện Tri Tôn', 'Huyện', 89, NULL, NULL),
(892, 'Huyện Châu Thành', 'Huyện', 89, NULL, NULL),
(893, 'Huyện Chợ Mới', 'Huyện', 89, NULL, NULL),
(894, 'Huyện Thoại Sơn', 'Huyện', 89, NULL, NULL),
(899, 'Thành phố Rạch Giá', 'Thành phố', 91, NULL, NULL),
(900, 'Thị xã Hà Tiên', 'Thị xã', 91, NULL, NULL),
(902, 'Huyện Kiên Lương', 'Huyện', 91, NULL, NULL),
(903, 'Huyện Hòn Đất', 'Huyện', 91, NULL, NULL),
(904, 'Huyện Tân Hiệp', 'Huyện', 91, NULL, NULL),
(905, 'Huyện Châu Thành', 'Huyện', 91, NULL, NULL),
(906, 'Huyện Giồng Riềng', 'Huyện', 91, NULL, NULL),
(907, 'Huyện Gò Quao', 'Huyện', 91, NULL, NULL),
(908, 'Huyện An Biên', 'Huyện', 91, NULL, NULL),
(909, 'Huyện An Minh', 'Huyện', 91, NULL, NULL),
(910, 'Huyện Vĩnh Thuận', 'Huyện', 91, NULL, NULL),
(911, 'Huyện Phú Quốc', 'Huyện', 91, NULL, NULL),
(912, 'Huyện Kiên Hải', 'Huyện', 91, NULL, NULL),
(913, 'Huyện U Minh Thượng', 'Huyện', 91, NULL, NULL),
(914, 'Huyện Giang Thành', 'Huyện', 91, NULL, NULL),
(916, 'Quận Ninh Kiều', 'Quận', 92, NULL, NULL),
(917, 'Quận Ô Môn', 'Quận', 92, NULL, NULL),
(918, 'Quận Bình Thuỷ', 'Quận', 92, NULL, NULL),
(919, 'Quận Cái Răng', 'Quận', 92, NULL, NULL),
(923, 'Quận Thốt Nốt', 'Quận', 92, NULL, NULL),
(924, 'Huyện Vĩnh Thạnh', 'Huyện', 92, NULL, NULL),
(925, 'Huyện Cờ Đỏ', 'Huyện', 92, NULL, NULL),
(926, 'Huyện Phong Điền', 'Huyện', 92, NULL, NULL),
(927, 'Huyện Thới Lai', 'Huyện', 92, NULL, NULL),
(930, 'Thành phố Vị Thanh', 'Thành phố', 93, NULL, NULL),
(931, 'Thị xã Ngã Bảy', 'Thị xã', 93, NULL, NULL),
(932, 'Huyện Châu Thành A', 'Huyện', 93, NULL, NULL),
(933, 'Huyện Châu Thành', 'Huyện', 93, NULL, NULL),
(934, 'Huyện Phụng Hiệp', 'Huyện', 93, NULL, NULL),
(935, 'Huyện Vị Thuỷ', 'Huyện', 93, NULL, NULL),
(936, 'Huyện Long Mỹ', 'Huyện', 93, NULL, NULL),
(937, 'Thị xã Long Mỹ', 'Thị xã', 93, NULL, NULL),
(941, 'Thành phố Sóc Trăng', 'Thành phố', 94, NULL, NULL),
(942, 'Huyện Châu Thành', 'Huyện', 94, NULL, NULL),
(943, 'Huyện Kế Sách', 'Huyện', 94, NULL, NULL),
(944, 'Huyện Mỹ Tú', 'Huyện', 94, NULL, NULL),
(945, 'Huyện Cù Lao Dung', 'Huyện', 94, NULL, NULL),
(946, 'Huyện Long Phú', 'Huyện', 94, NULL, NULL),
(947, 'Huyện Mỹ Xuyên', 'Huyện', 94, NULL, NULL),
(948, 'Thị xã Ngã Năm', 'Thị xã', 94, NULL, NULL),
(949, 'Huyện Thạnh Trị', 'Huyện', 94, NULL, NULL),
(950, 'Thị xã Vĩnh Châu', 'Thị xã', 94, NULL, NULL),
(951, 'Huyện Trần Đề', 'Huyện', 94, NULL, NULL),
(954, 'Thành phố Bạc Liêu', 'Thành phố', 95, NULL, NULL),
(956, 'Huyện Hồng Dân', 'Huyện', 95, NULL, NULL),
(957, 'Huyện Phước Long', 'Huyện', 95, NULL, NULL),
(958, 'Huyện Vĩnh Lợi', 'Huyện', 95, NULL, NULL),
(959, 'Thị xã Giá Rai', 'Thị xã', 95, NULL, NULL),
(960, 'Huyện Đông Hải', 'Huyện', 95, NULL, NULL),
(961, 'Huyện Hoà Bình', 'Huyện', 95, NULL, NULL),
(964, 'Thành phố Cà Mau', 'Thành phố', 96, NULL, NULL),
(966, 'Huyện U Minh', 'Huyện', 96, NULL, NULL),
(967, 'Huyện Thới Bình', 'Huyện', 96, NULL, NULL),
(968, 'Huyện Trần Văn Thời', 'Huyện', 96, NULL, NULL),
(969, 'Huyện Cái Nước', 'Huyện', 96, NULL, NULL),
(970, 'Huyện Đầm Dơi', 'Huyện', 96, NULL, NULL),
(971, 'Huyện Năm Căn', 'Huyện', 96, NULL, NULL),
(972, 'Huyện Phú Tân', 'Huyện', 96, NULL, NULL),
(973, 'Huyện Ngọc Hiển', 'Huyện', 96, NULL, NULL);


